## https://github.com/prometheus-community/helm-charts/tree/main/charts
grafana:
  enabled: false

# nameOverride: kps
fullnameOverride: kps 

prometheus:
  service:
    enabled: true
    type: NodePort
  prometheusSpec:
    nodeSelector:
      role: system
    scrapeInterval: "30s" # Defaults to 30s
    scrapeTimeout: "10s" # Number of seconds to wait for target to respond before erroring
    evaluationInterval: "1m" # Interval between consecutive evaluations.
    ## External labels to add to any time series or alerts when communicating with external systems
    externalLabels: 
      cluster: ${EKS_CLUSTER_NAME}
    image:
      registry: quay.io
      repository: prometheus/prometheus
    serviceMonitorSelectorNilUsesHelmValues: true
    retention: "15d" # How long to retain metrics
    storageSpec:
    ## https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/storage.md
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi # 联动 retention 的配置，合理设置大小
    additionalScrapeConfigs: |
      - job_name: karpenter
        kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - karpenter
        relabel_configs:
        - source_labels: [__meta_kubernetes_endpoint_port_name]
          regex: http-metrics
          action: keep

alertmanager:
  enabled: true
  alertmanagerSpec:
    nodeSelector:
      role: system
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/storage.md
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
