# Pyroscope eBPF agent 以 daemonset 的方式部署在每一个 EKS 节点上，使用 Kubernetes 的服务发现机制获取 Pod 列表，通过配置规则对采集的数据执行 relabel
# https://grafana.com/docs/pyroscope/latest/configure-client/grafana-agent/ebpf/
# https://grafana.com/docs/agent/latest/flow/reference/components/discovery.kubernetes/
#           url = "http://pyroscope.otel.svc.cluster.local:4040"
agent:
  mode: 'flow'
  configMap:
    create: true
    content: |
      discovery.kubernetes "all_pods" {
        selectors {
          field = "spec.nodeName=" + env("HOSTNAME")
          role = "pod"
        }
        role = "pod"
      }
      discovery.relabel "local_pods" {
        targets = discovery.kubernetes.all_pods.targets
        rule {
          action = "replace"
          replacement = "${1}/${2}"
          separator = "/"
          source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_pod_container_name"]
          target_label = "service_name"
        }
      }
      pyroscope.ebpf "local_pods" {
        forward_to = [ pyroscope.write.endpoint.receiver ]
        targets = discovery.relabel.local_pods.output
      }
      pyroscope.write "endpoint" {
        endpoint {
          url = "http://pyroscope:4040"
        }
      }

  securityContext:
    privileged: true
    runAsGroup: 0
    runAsUser: 0

controller:
  hostPID: true

## https://hub.docker.com/r/grafana/agent
image:
  registry: "docker.io"
  repository: grafana/agent
  tag: v0.36.2 # v0.36.2

